# Use a default python:3.5 docker image as a parent image
FROM python:3.5

MAINTAINER Lina Qiu <lqiu@ece.ubc.ca>

# Copy the current directory contents into the container 
ADD . /scripts/

# Set the working directory to ../scripts
WORKDIR /scripts/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80 

ENTRYPOINT ["/bin/bash"]
